### ISSUE TITLE
Minor patch to get it to work

### ISSUE THREAD

**Issue by ktjn** [marksl/DotNetFlumeNG.Clients#1]
For me userdomainname is not a valid hostname and timestamp is never set.

GetHostname might be better?

diff --git a/DotNetFlumeNG.Client.NLog/Core/LogEvent.cs b/DotNetFlumeNG.Client.NLog/Core/LogEvent.cs
index d26163c..4ea4545 100644
--- a/DotNetFlumeNG.Client.NLog/Core/LogEvent.cs
+++ b/DotNetFlumeNG.Client.NLog/Core/LogEvent.cs
@@ -47,8 +47,7 @@ public string Host
         {
             get
             {
-                IPHostEntry he = Dns.GetHostEntry(Environment.UserDomainName);
-                return he.HostName;
-                return Dns.GetHostName();
           }
       }

diff --git a/DotNetFlumeNG.Client.NLog/NLog/NLogEventAdapter.cs b/DotNetFlumeNG.Client.NLog/NLog/NLogEventAdapter.cs
index b0b6d12..9607e4e 100644
--- a/DotNetFlumeNG.Client.NLog/NLog/NLogEventAdapter.cs
+++ b/DotNetFlumeNG.Client.NLog/NLog/NLogEventAdapter.cs
@@ -34,6 +34,8 @@ public NLogEventAdapter(string message, LogEventInfo logEventInfo)

```
         _message = message;
         _logEventInfo = logEventInfo;
```

+
- ```
         this.Timestamp = logEventInfo.TimeStamp;
   }
  
   public override LogPriority Priority
  ```

**Comment by marksl** [comment]
Thanks a lot tommy. I have a similar change locally that I was trying. My flume integration was stalled at work so I haven't had time to patch it. When I'm back from holiday I'll integrate the patch and push a new build to nuget. 

Thanks again!
Mark

**Comment by ktjn** [comment]
I have some additional fixes as well. I might do a fork and create a pull request instead.

**Comment by marksl** [comment]
I committed a slightly modified fix. Thanks again. I'm interested to hear your other improvements too.

**Comment by ktjn** [comment]
thanks. I will :-)
