### ISSUE TITLE
One more minor fix

### ISSUE THREAD

**Issue by ktjn** [marksl/DotNetFlumeNG.Clients#2]
diff --git a/DotNetFlumeNG.Client.NLog/NLog/NLogEventAdapter.cs b/DotNetFlumeNG.Client.NLog/NLog/NLogEventAdapter.cs
index 5dffdc7..eabf0f3 100644
--- a/DotNetFlumeNG.Client.NLog/NLog/NLogEventAdapter.cs
+++ b/DotNetFlumeNG.Client.NLog/NLog/NLogEventAdapter.cs
@@ -28,13 +28,14 @@ public class NLogEventAdapter : LogEvent
         private readonly string _message;

```
     public NLogEventAdapter(string message, LogEventInfo logEventInfo)
```
-            : base(logEventInfo.TimeStamp)
- ```
         : base(logEventInfo.TimeStamp.ToUniversalTime())
   {
       if (message == null) throw new ArgumentNullException("message");
       if (logEventInfo == null) throw new ArgumentNullException("logEventInfo");
  
       _message = message;
       _logEventInfo = logEventInfo;
  ```
  
  +
       }
  
  ```
   public override LogPriority Priority
  ```
  
  diff --git a/DotNetFlumeNG.Client.NLog/Thrift/ThriftFlumeEventAdapter.cs b/DotNetFlumeNG.Client.NLog/Thrift/ThriftFlumeEventAdapter.cs
  index a217e34..d0d0df7 100644
  --- a/DotNetFlumeNG.Client.NLog/Thrift/ThriftFlumeEventAdapter.cs
  +++ b/DotNetFlumeNG.Client.NLog/Thrift/ThriftFlumeEventAdapter.cs
  @@ -19,6 +19,8 @@
  
  namespace DotNetFlumeNG.Client.Thrift
  {
-    using System.Text;
  +
   public class ThriftFlumeEventAdapter : ThriftFlumeEvent
   {
       public ThriftFlumeEventAdapter(LogEvent logEvent)
  @@ -70,9 +72,7 @@ private void SetFields(LogEvent logEvent)
  
  ```
   private static byte[] GetBytes(string str)
   {
  ```
-            var bytes = new byte[str.Length*sizeof (char)];
-            Buffer.BlockCopy(str.ToCharArray(), 0, bytes, 0, bytes.Length);
-            return bytes;
- ```
         return Encoding.Default.GetBytes(str);
   }
  ```
  
   }
  }
- Set logtime to UTC
- default encoding, instead of unicode

**Comment by marksl** [comment]
Fixed. Thanks again again. :+1:

**Comment by ktjn** [comment]
Excellent work btw :-) We now have a nlog -> flume -> elasticsearch -> kibana setup that works.

**Comment by marksl** [comment]
Great and that's hilarious. That's exactly what I'm using it for too!
